version: '3.9'

services:
  # Redis master nodes
  redis-master-1:
    image: redis:6.0.9
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "7000:6379"
    networks:
      - redis-cluster-net

  redis-master-2:
    image: redis:6.0.9
    ports:
      - "7001:6379"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    networks:
      - redis-cluster-net

  redis-master-3:
    image: redis:6.0.9
    ports:
      - "7002:6379"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    networks:
      - redis-cluster-net

  # Redis replica nodes
  redis-replica-1:
    image: redis:6.0.9
    ports:
      - "7003:6379"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    networks:
      - redis-cluster-net

  redis-replica-2:
    image: redis:6.0.9
    ports:
      - "7004:6379"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    networks:
      - redis-cluster-net

  redis-replica-3:
    image: redis:6.0.9
    ports:
      - "7005:6379"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    networks:
      - redis-cluster-net

  redis-exporter-1:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis-master-1:6379
    depends_on:
      - redis-master-1
    networks:
      - redis-cluster-net

  redis-exporter-2:
    image: oliver006/redis_exporter:latest
    ports:
      - "9122:9121"
    environment:
      - REDIS_ADDR=redis://redis-master-2
    depends_on:
      - redis-master-2
    networks:
      - redis-cluster-net
  
  redis-exporter-3:
    image: oliver006/redis_exporter:latest
    ports:
      - "9123:9121"
    environment:
      - REDIS_ADDR=redis://redis-master-3
    depends_on:
      - redis-master-3
    networks:
      - redis-cluster-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    depends_on:
      - redis-exporter-1
      - redis-exporter-2
      - redis-exporter-3
    networks:
      - redis-cluster-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - ./grafana/config
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
    driver: bridge