
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  jsonData:
    tlsAuth: false
    tlsAuthWithCACert: false
  editable: true