
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  jsonData:
    tlsAuth: false
    tlsAuthWithCACert: false
  editable: true
- name: Redis
  type: redis-datasource
  access: proxy
  orgId: 1
  version: 1
  url: redis://redis-master-1:6379
  jsonData:
    client: standalone
    poolSize: 3
    timeout: 10
    pingInterval: 0
    pipelineWindow: 0
  editable: true